CREATE DATABASE ITTVT_Pacman WITH TEMPLATE = template0 ENCODING = 'UTF8';


ALTER DATABASE ITTVT_Pacman SET "TimeZone" TO 'UTC';
ALTER DATABASE ITTVT_Pacman CONNECTION LIMIT -1;
-- ALTER DATABASE ITTVT_Pacman OWNER TO "%(owner)s";
\connect ITTVT_Pacman;

CREATE TABLE Tags(
    ID SERIAL PRIMARY KEY,
    Name VARCHAR(32) UNIQUE
);

CREATE TABLE Worlds(
    MD5 VARCHAR(32) NOT NULL PRIMARY KEY,
    World BYTEA NOT NULL,
    Title VARCHAR(32) NOT NULL,
    ImgPreview BYTEA NOT NULL
);

CREATE INDEX BTREE ON Worlds(Title);

CREATE TABLE WorldsTags(
    ReferToWorld VARCHAR(32) REFERENCES Worlds(MD5),
    ReferToTag INT REFERENCES Tags(ID),
    UNIQUE (ReferToWorld, ReferToTag)
);
